name: Generate Contribution Snakes

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Personal Snake
      - name: Generate Personal Snake
        uses: Platane/snk@v3
        with:
          github_user_name: hasnat-hassan
          outputs: |
            dist/personal/github-snake.svg
            dist/personal/github-snake-dark.svg?palette=github-dark

      # Company Snake
      - name: Generate Company Snake
        uses: Platane/snk@v3
        with:
          github_user_name: hasnat-rx
          outputs: |
            dist/company/github-snake.svg
            dist/company/github-snake-dark.svg?palette=github-dark

      # Publish both snakes
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}